### ISSUE TITLE
Bug: Timer reduced by 1 sec on orientation change when paused

### ISSUE THREAD

**Issue by cherylli** [cherylli/pomodoro-kotlin#26]
Only for the first time, subsequeint orientation changes are ok

**Comment by cherylli** [comment]
I'm actually not quite sure how to fix it as it only happens on first orientation change. Maybe I can add a flag to tell if its the first orientation change. If yes then I add 1 sec to the timer?

**Comment by yatw** [comment]
I have an idea, this 1 second diff is because we first display and then subtract 1 from timer as I explained earlier. So if we switch the order to subtract 1 first, then display, the display value and actual timer value will be consistent.

If counting from 10, switching the order will make timer
subtract 1 from 10, display a 9
subtract 1 from 9, display a 8
so we are displaying from 9, missing 10

But if we display 10 when user set the timer before the timer run. It will looks fine.

Since the 2 issues is kind of related, I am gonna address them both

**Comment by cherylli** [comment]
That was an easy fix ....Yes it looks fine
